### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by pwalker91** [cliffrowley/atom-open-in-github-app#4]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Utilities (Other)/Atom.app/Contents/Resources/app/src/atom.js:53:11)
Object.activate (/Users/peterwalker/.atom/packages/open-in-github-app/lib/open-in-github-app.coffee:6:9)
```

**Comment by jugglingnutcase** [comment]
Thanks for letting us know!

The line you've pointed to tells our package how to handle our `open-in-github-app` command. Looks like (from the [package generator stuff](https://github.com/atom/apm/blob/b9294e955e783fe1b0b50180fd02ceef989bfcc2/templates/package/lib/__package-name__.coffee.template#L16-17)) instead we should be adding a command subscription.

Would you be able to put together a pull request that adds those subscriptions? i can help you if you need.

Thanks again :smile:

**Comment by pwalker91** [comment]
Hi. Sorry for not responding so quickly. I haven't work with github very much, so I'm a little confused. Could you explain to me what I should do for this issue?
Thanks for the help and understanding.

**Comment by jugglingnutcase** [comment]
No problem!

[Looks like the open-in-github-app.coffee file on line 6](https://github.com/cliffrowley/atom-open-in-github-app/blob/master/lib/open-in-github-app.coffee#L6) is what throws the issue. i was wondering if you wanted to try to fix the error and submit it to us for inclusion via a pull request.

GitHub has [a guide on contributing to a project](https://guides.github.com/activities/contributing-to-open-source/#contributing) that might help you get started with forking this project, making fixes, and submitting them as a pull request.

If all of this sounds like too much, let me know. i wouldn't mind taking care of this, i just want to give you an opportunity to fix it first :smile:
