### ISSUE TITLE
Project.getPath is deprecated.

### ISSUE THREAD

**Issue by zimme** [cliffrowley/atom-open-in-github-app#6]
Use ::getPaths instead
```
Project.getPath (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/project.js:235:12)
Object.openApp (/Users/zimme/.atom/packages/open-in-github-app/lib/open-in-github-app.coffee:9:26)
```

**Comment by jugglingnutcase** [comment]
Thanks for the report :smile:

**Comment by zimme** [comment]
No problem, would have made a PR if I wasn't working on my own packages :stuck_out_tongue_closed_eyes:

**Comment by cliffrowley** [comment]
Let's fix this after https://github.com/cliffrowley/atom-open-in-github-app/issues/7 and https://github.com/cliffrowley/atom-open-in-github-app/issues/10

**Comment by zimme** [comment]
:+1:

**Comment by cliffrowley** [comment]
Fixed by https://github.com/cliffrowley/atom-open-in-github-app/pull/12
