### ISSUE TITLE
Support multiple folders

### ISSUE THREAD

**Issue by jugglingnutcase** [cliffrowley/atom-open-in-github-app#7]
Via http://blog.atom.io/2015/04/15/multi-folder-projects.html

**Comment by cliffrowley** [comment]
Oh that's cool.  Had no idea Atom could do this.

**Comment by cliffrowley** [comment]
Hey @jugglingnutcase - just letting you know that I have just updated https://github.com/cliffrowley/atom-open-in-sourcetree to support multiple project folders, and tidied up the code a bit.  I'm happy to update this package too, or equally happy for you to take a look at what I did over there and have it it yourself :-)

**Comment by jugglingnutcase** [comment]
If you've already got something in place, let's do that. i've just got half-baked ideas and a tiny bit of code!

**Comment by jugglingnutcase** [comment]
It looks like what you have there is what i was planning already... though you use atom-space-pen-views huh. i've seen it but never tried using it. Was it fairly easy to grasp?

**Comment by cliffrowley** [comment]
Yeah, though I'm only using it to pop up a list if there is more than one project folder.

**Comment by jugglingnutcase** [comment]
That's all it needs I think.

**Comment by cliffrowley** [comment]
Fixed by https://github.com/cliffrowley/atom-open-in-github-app/pull/12
