### ISSUE TITLE
Project.getRepo is deprecated.

### ISSUE THREAD

**Issue by jugglingnutcase** [cliffrowley/atom-open-in-github-app#8]
Use ::getRepositories instead
```
Project.getRepo (C:\Users\james_000\AppData\Local\atom\app-0.192.0\resources\app\src\project.js:579:12)
Object.openApp (C:\Users\james_000\.atom\packages\open-in-github-app\lib\open-in-github-app.coffee:14:26)
```

**Comment by jugglingnutcase** [comment]
@cliffrowley, i'm working on stuff that will fix this and #6, but it was a lot bigger of a thing than i anticipated. Perhaps i could use to simplify it. i'll try to get it published soon for review.

**Comment by cliffrowley** [comment]
Let's fix this after https://github.com/cliffrowley/atom-open-in-github-app/issues/7 and https://github.com/cliffrowley/atom-open-in-github-app/issues/10

**Comment by cliffrowley** [comment]
Fixed by https://github.com/cliffrowley/atom-open-in-github-app/pull/12
